### ISSUE TITLE
[LEAGUE LOADER]: Could not find league for year 2022 with ID

### ISSUE THREAD

**Issue by tprusisz** [joeyagreco/leeger#108]
### League Loader

Yahoo

### Summary

The League Loader does not look like it is pulling previous seasons from Yahoo properly. I am getting the error message: Could not find league for year 2022 with ID (414, 957486).

It looks like when Yahoo gives the League Loader the 'previousLeagueID', it gives a vector of 2 numbers (in my case [414, 957486]). The 957486 value is the correct value for the ID of my league in 2022. But, the script throws this error because instead of just trying to match 957486, it is looking to match the entire vector (414, 957486). If I manually change the 'currentLeagueId' from the vector to only 957486 right as it does the check on line 100 of YahooLeagueLoader.py, then it all seems to run fine. So, I'm not sure where the 414 is coming from, but it looks like when updating the 'previousLeagueId' on Line 103, it should only grab the second number in the vector, and convert it to a string. Something like:

previousLeagueId = str(league.past_league_id[2])

### League Info

Yahoo
2023 League ID: 382757
2022 League ID: 957486

**Comment by joeyagreco** [comment]
This should be resolved by this: https://github.com/joeyagreco/leeger/releases/tag/v2.5.4

Make sure to run `python -m pip install leeger --upgrade`
