### ISSUE TITLE
[LEAGUE LOADER]: ESPN Loader throwing 403

### ISSUE THREAD

**Issue by kylehild** [joeyagreco/leeger#133]
### League Loader

ESPN

### Summary

ESPN Loader is throwing 403 errors because ESPN changed threir supported endpoint. The espn_api that is used has fixed it's underlying implementation in [version 0.36.0](https://github.com/cwendt94/espn-api/releases/tag/v0.36.0). It looks like dependabot is finding that there is a new version, but it isn't submitting a pull request to update it. Can we update it manually?

### League Info

All leagues fail

### Error Logs

ESPN returns a 403

**Comment by joeyagreco** [comment]
Thank you @kylehild

**Comment by joeyagreco** [comment]
Fixed in [this release](https://github.com/joeyagreco/leeger/releases/tag/v2.7.0)
