### ISSUE TITLE
[LEAGUE LOADER]:  Yahoo league loader unable to find more than 1 league year

### ISSUE THREAD

**Issue by brian-dev8** [joeyagreco/leeger#27]
### League Loader

Yahoo

### Summary

The yahoo league ids change every year so it is only able to find the first year, and then leeger fails when the script detects not all years were found.

### Error Logs

`Error
Traceback (most recent call last):
  File "C:\D\windows\git\leeger\test\test_league_loader\test_YahooLeagueLoader.py", line 46, in test_league
    league: League = yahooLeagueLoader.loadLeague()
  File "C:\D\windows\git\leeger\leeger\league_loader\YahooLeagueLoader.py", line 69, in loadLeague
    raise DoesNotExistException(f"Found {len(yahooLeagues)} years, expected to find {len(self._years)}.")
leeger.exception.DoesNotExistException.DoesNotExistException: Found 1 years, expected to find 2.
`

**Comment by joeyagreco** [comment]
This is now fixed in [version 1.3.0](https://github.com/joeyagreco/leeger/releases/tag/v1.3.0)
